---
title: "Sondes_Thermiques"
author: "Yves-Marie Heno"
date: "2025-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
library(rnaturalearth)
library(mapview)
library(leaflet)
source("Localisation_sondes.R")
source("proposition_sondes.R")

```

```{r image,echo=FALSE}

```

## Introduction
ci dessous un document de lavorisation des sondes thermiques en continu équipées sur les stations
Hydrométriques de la DREAL

# Localisation des sondes

```{r Localisation,echo=FALSE,fig.width=10,message=FALSE}
sites <- Localisation_sondes()
codes_sites_proposes <- read.csv2('../Data/propositiondesites.csv')  %>% 
  as.data.frame()


#fonds de carte bretagne
Bretagne <- ne_states(country = "France", returnclass = "sf") %>% 
  filter(region=="Bretagne")
stationshydro <- filter(sites,sonde_thermique=='NON')
sondesthermiques <- filter(sites,sonde_thermique=='OUI')

#stationspeche
stationspeches <- readxl::read_xlsx('../Data/Tab_Pêches_prog2026_2027_10_2025.xlsx',sheet=2,col_names = T) %>% 
  slice(-(1:6)) %>%
  select(3,6:9)
stationspeches <-    filter(stationspeches, stationspeches$...3 %in% c("22","29","35","56")) %>% select(2:5) 
colnames(stationspeches) <- c("code","libelle","X","Y")
stationspeches <- stationspeches %>% drop_na()
stationspeches <- stationspeches  %>% 
  st_as_sf( coords=c("X","Y"),crs=2154) %>% 
  st_transform(4326) 


mapview(Bretagne,zcol='name',legend=FALSE,label=FALSE,alpha.regions=0.1,popup=FALSE)+
mapview(stationshydro,layer.name = "sites hydrométrie", popup=leafpop::popupTable(stationshydro,zcol=c('code_station','libelle_station')), cex=3,col.regions='blue',label=stationshydro$libelle_station, labelOptions = labelOptions(noHide = FALSE, textOnly = TRUE ))+
  mapview(sondesthermiques,layer.name = "sondes thermiques en place", popup=leafpop::popupTable(sondesthermiques,zcol=c('code_station','libelle_station')), cex=6,col.regions='red', label=sondesthermiques$libelle_station,   labelOptions = labelOptions(noHide = T, textOnly = TRUE ))+
  mapview(stationspeches,layer.name = "Stations pelec", popup=leafpop::popupTable(stationspeches,zcol=c('code','libelle')), cex=3,col.regions='green', label=stationspeches$libelle,   labelOptions = labelOptions(noHide = F, textOnly = TRUE ))
 
sondesthermiques <- st_drop_geometry(sondesthermiques)

datatable(sondesthermiques[,3:2],options =
            list(pageLength = 30,
                  iDisplayLength=10,
                  bPaginate=TRUE,                  
                  bLengthChange=TRUE,                       
                  bFilter=F ,                                   
                  bInfo=FALSE,
                  rowid = FALSE,
                  autoWidth = FALSE,
                 ordering = TRUE,
                  scrollX = TRUE,
                  borders = TRUE,
                 columnDefs = list(list(className = 'dt-center', targets ="_all"))
                 ),rownames=FALSE#enlever le numero des lignes
          )

```
## Sites proposées mais sans station hydro
(Donc non retenus)  
aër au Croisty  


## Pour info : Liste des sites hydrométriques
```{r Listing sites équipés,echo=FALSE}
sitesl <- select(sites,c(1,2,5)) %>% 
  sf::st_drop_geometry()  %>% unique()
datatable(sitesl,options =
            list(pageLength = 30,
                  iDisplayLength=10,
                  bPaginate=TRUE,                  
                  bLengthChange=TRUE,                       
                  bFilter=TRUE ,                                   
                  bInfo=FALSE,
                  rowid = FALSE,
                  autoWidth = FALSE,
                 ordering = TRUE,
                  scrollX = TRUE,
                  borders = TRUE,
                 columnDefs = list(list(className = 'dt-center', targets ="_all"))
                 ),rownames=FALSE#enlever le numero des lignes
          )


```
